version: "3.8"
services:
  mq:
    image: mq:0.1.0
    build:
      context: ./mq/
    hostname: mq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    image: api:0.1.0
    build:
      context: ./api/
    hostname: api
    env_file:
      - .env
    ports:
      - "9090:9090"
    depends_on:
      - mq
    links:
      - mq

  web:
    image: web:0.1.0
    build:
      context: ./web/
    hostname: web
    ports:
      - "8080:80"
    depends_on:
      - api